### ISSUE TITLE
User signIn and login

### ISSUE THREAD

**Issue by prateekmohanty63** [coding-geek21/classDeck#23]
There seems to be some glitch in user sign in and login .
Password and confirm password are the same still the account is not getting created.

I will build the complete user registration and login feature in the backend and take care of all the glitches

Please assign me this issue under GSSOC22

**Comment by yaswanthsaivendra** [comment]
Yaa this isn't an expected behaviour. @coding-geek21 , Can you give some insights on this?
@prateekmohanty63 Anyway, for further proceedings with the project, the user registration has to be redefined . This time email is included (possibly with verification). If you can do that this will be assigned as `level3` issue under `GSSOC22` .

**Comment by prateekmohanty63** [comment]
Yeah sure assign me this .
I will do it

**Comment by prateekmohanty63** [comment]
@yaswanthsaivendra

**Comment by coding-geek21** [comment]
> There seems to be some glitch in user sign in and login . Password and confirm password are the same still the account is not getting created.
> 
> I will build the complete user registration and login feature in the backend and take care of all the glitches
> 
> Please assign me this issue under GSSOC22

@prateekmohanty63  Hey that's actually because in sign up page we have interests as a mandatory field. So you have to update the subjects by adding one or two subjects in admin panel.. so follow these steps

-  create superuser
-  Go to admin panel 
-  Under subjects table create one or more subjects (so it gets added to interests)
-  Try signing up now you wouldn't get any errors 

As @yaswanthsaivendra  said redefine the models by adding the email field for both teachers and students

Hope you get it

**Comment by prateekmohanty63** [comment]
oh wow thanks @coding-geek21  for the information , i was kinda of confused cause when i saw in the deployed version signin was working fine , but not in my local machine.

Yeah I will add the email things . Thank you

**Comment by prateekmohanty63** [comment]
@coding-geek21  I had one more doubt , like I have added the email field and taking it as input during registration.
Should I also send verification mail to user once the user has registered?

Like can you exactly define the requirements ?

**Comment by prateekmohanty63** [comment]
Or do i just send to check if the email being entered is correct?

**Comment by coding-geek21** [comment]
> @coding-geek21 I had one more doubt , like I have added the email field and taking it as input during registration. Should I also send verification mail to user once the user has registered?
> 
> Like can you exactly define the requirements ?

You have to send a User authentication link to the mail id specified by the user  so that they can confirm their account by clicking on the link they received 
Once they confirm account will be created for them

**Comment by prateekmohanty63** [comment]
ok cool got it , thanks

**Comment by prateekmohanty63** [comment]
@coding-geek21  I have completed the thing
Here is the output
![image](https://user-images.githubusercontent.com/72243320/156700636-43a34627-04f8-4fdb-beba-c3780f6eb6d0.png)

**Comment by prateekmohanty63** [comment]
![image](https://user-images.githubusercontent.com/72243320/156700712-5a9c599b-baba-45b7-824a-b52ebb40e066.png)

**Comment by coding-geek21** [comment]
Ok @prateekmohanty63  make PR

**Comment by prateekmohanty63** [comment]
![image](https://user-images.githubusercontent.com/72243320/156I701121-991af3a9-44b0-467d-a925-a607cc420590.png)i I have hidden  my credentials , put your and it would work fine

**Comment by prateekmohanty63** [comment]
in setting.py

**Comment by prateekmohanty63** [comment]
@coding-geek21  which branch should I send a pr

**Comment by coding-geek21** [comment]
> @coding-geek21 which branch should I send a pr

develop branch

**Comment by prateekmohanty63** [comment]
@coding-geek21 I have sent the pr
Please merge it
Thank you
