### ISSUE TITLE
Create previous and next button feature in quiz page

### ISSUE THREAD

**Issue by coding-geek21** [coding-geek21/classDeck#48]
## Is your feature request related to a problem? Please describe.

Currently we have only next button, on clicking next button it submits the answer and moves to next question 
**Problem:** User is not able to move to previous or next question without answering the current question

## Describe the solution you'd like...

- You must make the previous and next button feature so that the user moves to the previous or next question 
- Add the save button to save the answer 

## Approach to be followed (optional):

A clear and concise description of the approach to be followed.

## Screenshots Or Video

![image](https://user-images.githubusercontent.com/53329034/156928225-4041cdac-46d7-4a1b-90bd-803c80694b9a.png)

Attach screenshots or video if applicable

**Comment by sripor62** [comment]
Hii ! I would like to work on this .Can I be assigned !

**Comment by coding-geek21** [comment]
> Hii ! I would like to work on this .Can I be assigned !

Yes go ahead!

**Comment by coding-geek21** [comment]
@sripor62 Any updates??

**Comment by coding-geek21** [comment]
@sripor62 Any updates?

**Comment by m-a-rahul** [comment]
Hi! I'm interested to work on it! Could you assign it to me?

**Comment by coding-geek21** [comment]
Go ahead @m-a-rahul

**Comment by m-a-rahul** [comment]
Hey @coding-geek21 

I met with the challenge while customising this feature and I want your help with that. First of all, I will share my progress.

### Progress
1. Added two buttons namely, `PREVIOUS` and `NEXT` which has been even validated against boundary conditions.
2. Along with that I've added the dashboard that displays a range of numbers according to the total no of questions in the quiz.
3. Also, the saved answers will be highlighted in green.
4. On clicking the `SAVE` button the particular answer gets saved and the user is redirected to the first index of the unanswered questions.

![image](https://user-images.githubusercontent.com/60550746/158991345-77ad018a-74bb-42d1-8945-5220e834b788.png)

#### Issues Faced

So I am trying to display an update form if the user wants to revisit the saved question but since there are no connections between the **Questions** and the **Answers** table in the quiz I am not able to identify the particular instance and render an _Update form_.

#### Solution Discussion

According to my point of view, It might not be feasible to run a quiz application where there is no direct relation between the particular questions and the corresponding set of answers. So, we should update the quiz input pattern or the way we gather questions and answers from the faculties. 

Kindly, write back at your convenience

**Comment by coding-geek21** [comment]
Yeah i got the point.. you can update the quiz in such a way that you can take the options (4 options) in Quiz table itself so you need to update the models for which you can create another level3 issue and work on it after working on that you can come here make changes and make PR @m-a-rahul

**Comment by m-a-rahul** [comment]
Thanks for acknowledging the query will follow the instructions provided and get back to you once I am complete @coding-geek21

**Comment by m-a-rahul** [comment]
> Yeah i got the point.. you can update the quiz in such a way that you can take the options (4 options) in Quiz table itself so you need to update the models for which you can create another level3 issue and work on it after working on that you can come here make changes and make PR @m-a-rahul

Hey, I've actually customised the functionality without creating that new direct relation between the table and created the pull request. Try going through the changes at your convenience, if it meets your expectations then we can cancel the new issue  #69 created.
